### ISSUE TITLE
studentWithTeacher route

### ISSUE THREAD

**Issue by DSFrey** [EvaGraceSmith/api-server#12]
https://github.com/EvaGraceSmith/api-server/blob/05bcf5fef2e696b2f29c0ca9eb4d55fedee0b3fd/src/models/collection.js#L62-L64
make sure you are receiving the argument that you called the method with:
https://github.com/EvaGraceSmith/api-server/blob/05bcf5fef2e696b2f29c0ca9eb4d55fedee0b3fd/src/routes/student.js#L15-L17
https://github.com/EvaGraceSmith/api-server/blob/05bcf5fef2e696b2f29c0ca9eb4d55fedee0b3fd/src/routes/student.js#L23-L27
Also, in the above snippets, remember that `teacher` is the Collection; to reference the actual model, you need `teacher.model`.
https://github.com/EvaGraceSmith/api-server/blob/05bcf5fef2e696b2f29c0ca9eb4d55fedee0b3fd/src/models/index.js#L19-L20
By default, sequelize uses the id column to create the foreign keys, so the options object is unnecessary and actually seems to be causing some problem.

**Comment by DSFrey** [comment]
When you write tests for the teachers, remember that they belong to a student, so you will need to post a student before you can post a teacher.

**Comment by EvaGraceSmith** [comment]
All tests are now passing.
I had to leave in the foreign key because because I am calling it "studentIds", instead of using the default id. 
I will attach a new submission.
