### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by DSFrey** [EvaGraceSmith/api-server#13]
https://github.com/EvaGraceSmith/api-server/blob/05bcf5fef2e696b2f29c0ca9eb4d55fedee0b3fd/src/models/collection.js#L16-L19
It's great that you are throwing the error here, but make sure you are completing the chain.
https://github.com/EvaGraceSmith/api-server/blob/05bcf5fef2e696b2f29c0ca9eb4d55fedee0b3fd/src/routes/student.js#L42-L46
We need another try/catch block here so the error doesn't crash the server. You can either send back a `res.status(500).send(error)` from here, or you can `next(error)` it on to a separate error handler.

**Comment by EvaGraceSmith** [comment]
Resolved these issues.
